server:
  port: 8098
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
    listener:
     simple:
      retry: 
       enabled: true
       initial-interval: 30s
       max-attempts: 60
       max-interval: 100s
       multiplier: 2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: notification
  

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true
        

rabbitmq: 
 exchange.name: bankNotification
 queue.name: bankNotification_Queue



