server:
  port: 8085
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest 
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: customermanagment
  datasource:
    url: jdbc:h2:mem:admin_dbDB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true
        

springdoc:
  api-docs:
    path: /customermanagment/v3/api-docs
    
  swagger-ui:
    enabled: false
    path: /customermanagment/swagger-ui.html
    
rabbitmq: 
 exchange.name: bankNotification
 queue.name: bankNotification_Queue
 routing.key: bankNotification_key
 deadLetterExchange.name: deadLetterExchange
 deadLetter.queue.name: dev_deadLetter_queue
 dead.routing.key: deadLetter      